// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCh8TXkSHNuig9NSAgxaCZPH6QFB2YiAg',
    appId: '1:670399834391:web:928ce14242572de3322f52',
    messagingSenderId: '670399834391',
    projectId: 'codepie-4db1a',
    authDomain: 'codepie-4db1a.firebaseapp.com',
    storageBucket: 'codepie-4db1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyIpaYd6Mg9_7093rNCguUNZl3rWgKduA',
    appId: '1:670399834391:android:e3c68adf7579bbda322f52',
    messagingSenderId: '670399834391',
    projectId: 'codepie-4db1a',
    storageBucket: 'codepie-4db1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZFZDQudLdd0Lo4xyGKhZVvgzwdXhyfc',
    appId: '1:670399834391:ios:0ce005541a706b3b322f52',
    messagingSenderId: '670399834391',
    projectId: 'codepie-4db1a',
    storageBucket: 'codepie-4db1a.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZFZDQudLdd0Lo4xyGKhZVvgzwdXhyfc',
    appId: '1:670399834391:ios:ed82ef1d7efe9772322f52',
    messagingSenderId: '670399834391',
    projectId: 'codepie-4db1a',
    storageBucket: 'codepie-4db1a.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
